POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Achara Chisom",
  "number": "040-2345678"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Achara Chisomu"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "040-2345678"
}

